### ISSUE TITLE
Add --no-interactive flag for headless use

### ISSUE THREAD

**Issue by pacoorozco** [gphotosuploader/gphotos-uploader-cli#102]
The idea of this feature is to implement a `--no-interactive` flag. Once `gphotos-uploader-cli` is called using this flag some configurations are changed behind scenes:

1. `SecretsBackendType` will be set to `file`, ignoring any other different value on config file.
1. The command line will use `KEYRING_ENCRYPTION_KEY` environment variable to encrypt/decrypt the secrets file. I agree that this is not the safest approach (see #86 for more details), but for working with sensitive data which you don’t want to show up in the history, it’s a good idea to work with environment variables, and a very common way to do it.

This will help using `gphotos-uploader-cli` in headless devices. **What do you think?**

Related with #86 and #15

**Comment by rfgamaral** [comment]
I've already expressed my opinion and concerns in #86 and I'll just reiterate them here:

### About the `--no-interactive` flag

I think this option will make everything more confusing and although I don't have an alternative at hand, I think other options should be explored.

I'm not very fond of an extra parameter that I need to remember to use which is forcing a different `SecretsBackendType` on the fly. I see this is a problem because if, for some reason, I call `gphotos-uploader-cli` without the parameter, it will now use the default `SecretsBackendType` option, which can be very different from `file` and now the user will no longer be authenticated.

This also adds a second and different way to configure the tool, parameters and the config file. IMO we should stick to only one way to configure the tool, to keep it simple and avoid edge cases as the one mentioned above.

A much better option, from my point of view at least, would be to extend `SecretsBackendType` with another option, let's call it `file2` for now (a better name is required). And if that option is set, use the `KEYRING_ENCRYPTION_KEY` approach, for instance (I still don't like, more on that below).

This would keep the configuration in **single place** (the configuration file) and would let the user pick whatever option is more suited to this usage without removing any of the available options.

### About the `KEYRING_ENCRYPTION_KEY`

The current proposal is to let the user pick it's own encryption key by setting this environment variable to whatever he/she sees fit. The only problem with this, **by supplying the key at run-time**, is that it barely serves any purpose at all. You might as well hard-code an encryption key as easy to guess as "password" because it provides the same amount of security. In other words, while the idea here is to give the user's control of their own security, there's no security at all by doing this.

If someone malicious gained access to the user's token, game over. This means the user's computer was compromised and thus the `KEYRING_ENCRYPTION_KEY` is stored in plain text somewhere in the computer (shell history, some configuration file, etc). **Implementing this option provides a false sense of security to the users.**

> (...)and a very common way to do it.

Yes, it's common to user environment variables to store sensitive data, but in a **completely different context than the one here**.

**Comment by pacoorozco** [comment]
> I'm not very fond of an extra parameter that I need to remember to use which is forcing a different SecretsBackendType on the fly. I see this is a problem because if, for some reason, I call gphotos-uploader-cli without the parameter, it will now use the default SecretsBackendType option, which can be very different from file and now the user will no longer be authenticated.

I agree, we probably follow one unique configuration file approach.

**Comment by monkeyhat** [comment]
Just wondered if there'd been any further thoughts on this?  Unfortunately, I don't have the technical expertise to help, but since Google (in their infinite wisdom) removed the automatic Google Drive -> Google Photos syncing, this is a SUPER useful solution.  

So far I've been using @rfgamaral's Docker image, but due to #103 I have to go through the manual Oauth process every time I run it.  I've tried running the Linux binary outside of Docker, but - as I'm doing this through SSH on a Synology NAS - I've been unable to get through the Oauth process.  

I just see a message telling me to go to a http://localhost:port URL, but as the Synology doesn't have a browser, I can't do this (and trying to access it as http://diskstation:port on another machine doesn't work, as it presumably needs to be accessed from the same IP.)  

I've tried curl-ing the URL in another SSH window on the NAS, and replacing the &amp;s in the resulting link with &s.  This gets me to the Google Oauth stuff, but when I complete that I don't seem to have a way to give the resulting localhost URL back to gphotos-uploader-cli.  If I try curl-ing it, I just end up with another Google Oauth link.  

Anyway, good luck with finding a solution to your current problems. I'm sure a working Dockerised version of this would be very popular!

**Comment by rfgamaral** [comment]
> I just see a message telling me to go to a http://localhost:port URL, but as the Synology doesn't have a browser, I can't do this (and trying to access it as http://diskstation:port on another machine doesn't work, as it presumably needs to be accessed from the same IP.)
> 
> I've tried curl-ing the URL in another SSH window on the NAS, and replacing the &s in the resulting link with &s. This gets me to the Google Oauth stuff, but when I complete that I don't seem to have a way to give the resulting localhost URL back to gphotos-uploader-cli. If I try curl-ing it, I just end up with another Google Oauth link.

There used to be a way to precisely do these manual steps and get the whole thing working for headless machines. However, latest changes completely blocked those workarounds because the authentication server only works on the machine it's actually running. Until this is changed, my Docker container will never work again.

To make the Docker container work again, the authentication server needs to listen on all interfaces (and not just `localhost`) and the port needs to be fixed (and not random). This would allow us to access that server from any machine in the same network by opening `http://<machine_with_gphotos_uploader_ip>:<port>`. This would make my Docker container work and any other headless machine too.

**Comment by rfgamaral** [comment]
@monkeyhat If you're interested, I've made some progress on my Docker container to get the authentication process working again. Still having the auth token expiration issue though and still trying to figure out why. Read more about it [here](https://github.com/rfgamaral/docker-gphotos-uploader/issues/8#issuecomment-531467044).

**Comment by pacoorozco** [comment]
I thinks this issue has been fixed with the work of @rfgamaral in his container.
