### ISSUE TITLE
Multiple album problem still occurs occasionally

### ISSUE THREAD

**Issue by mjhatcher** [gphotosuploader/gphotos-uploader-cli#135]
The multiple album issue reported under #19 is still occurring, although much less frequently. Before it would generate multiple albums, now what I'm seeing is that some but not all albums split in two.

**To Reproduce**
1. It needs at least 50 albums (default page size)
2. Run against a folder containing new albums
3. Instead of all images going into a single albums, the files are split across two albums both with the same name. Sometimes just one image goes into the second album; sometimes several do.

I think the issue could be a possible race condition when creating the albums caused by the multiple workers. Again, the problem goes away if only one upload is configured to run at once. I wonder if two workers both hit c.GetOrCreateAlbumByName at the same time they can both find that the album name does not exist, and then both create it. My go expertise isn't enough to troubleshoot concurrency issues, but looking back over the log it seems that two workers both create the album when they first start processing it, then all subsequent workers find the existing album correctly.

**Comment by pacoorozco** [comment]
I've found the problem and you're totally right.

When multiple workers call `GetOrCreateAlbumByName()` it could produce a race condition. One of the challenges is that Google Photos allow multiple albums with the same name, that's why this problem needs to be solved in the client.

I'm going to create an upstream issue to fix it: google-photos-api-client-go#26
