### ISSUE TITLE
Uploaded photo does not show correct file name

### ISSUE THREAD

**Issue by DrVanScott** [gphotosuploader/gphotos-uploader-cli#158]
I am using a self compiled version of commit 62bf509081de95c50cec86abc7824b1336cf489f (v1.0.0-alpha1)

Let's assume uploading a picture stored locally on

    /home/user/Daten/Bilder/2016_11_test/IMG_4729.JPG

After successful upload open the details of that picture from within the google photos web application. The result looks like this:

![gp_details](https://user-images.githubusercontent.com/1318728/68753851-f7c97680-0605-11ea-9e75-e8c22fcfc2e7.png)

While the info section displays the correct path & filename, the dedicated field for the filename shows "2019-11-13.jpg". This seems to be the date of upload. The expected value would be "IMG_4729.JPG"

**Comment by pacoorozco** [comment]
You're right, i've seen where the bug is... it's on gphotosuploader/google-photos-api-client-go#32

**Comment by pacoorozco** [comment]
Hi, It should be fixed from `v1.0.0-alpha2` or master :-D

**Comment by eGit** [comment]
I have a similar naming issue.

My upload folder is /home/egit/videos/uploads

Let's say I add the folder 'italy2019' (including many .mp4 videos) to the uploads folder. When I upload the videos it will create an album 'italy2019' (great!) but name the video:

/home/egit/videos/uploads/italy2019/beach.mp4

The expected file name should be just beach.mp4 and NOT the full path. Google Photos shows the full path. This might even be a small security issue since you leak your Linux user name ;)
