### ISSUE TITLE
Proxy Support

### ISSUE THREAD

**Issue by JanBoshoff** [gphotosuploader/gphotos-uploader-cli#176]
I am currently in a location in which I do not have direct access to Google services. I can however access Google services through a proxy server. I have tried to run gphotos-uploader-cli through proxychains, but that did not seem to work. Would it be feasible to provide proxy support for this project? Or is there another way in which I can still use it through a proxy server?

**Comment by pacoorozco** [comment]
Hi @JanBoshoff 
The problem is that to comple OAuth configuration phase you need a reverse proxy. This is the same problem that this CLI is having with headless installation. At this moment there is no plans to support this kind of scenarios, you can take a look to @rfgamaral project to see if it could help you: https://github.com/rfgamaral/docker-gphotos-uploader
