### ISSUE TITLE
Feedback: difficult to run on a headless server

### ISSUE THREAD

**Issue by JamieKitson** [gphotosuploader/gphotos-uploader-cli#202]
Hi,

I found this quite hard to init and run over ssh on a headless server.

1. The script opened a text browser. I have had no idea what this browser was or how to exit it, but because it didn't error I was never shown [the error message with the URL in](https://github.com/gphotosuploader/gphotos-uploader-cli/blob/2b5e2062df7f8205c5335dcd6e86b279b1833643/app/oauth.go#L80). I altered the program to show me the URL instead of opening the browser. Even if I had had a browser that worked on the server I would not have been able to use my U2F keys to authenticate.
2. I was not able to access the authorisation page externally so I had to create an ssh tunnel. I don't know if this is an issue with the program or with my network. Would it be possible to allow copy/pasting of urls rather than having to run the whole process through a browser?
3. When I run the program I am prompted for a password, even when the password is blank. Can I schedule this to run without interaction?

Thanks, Jamie

**Comment by pacoorozco** [comment]
Hi @JamieKitson 
This CLI is not intended to be run on a headless server due to several implementation details, mainly Google Photos authentication. For this reason I always highlight the great work that @rfgamaral has done [here](https://github.com/rfgamaral/docker-gphotos-uploader).

Just for your understanding. Points 1 and 2 corresponds to what is documented on [First time run](https://github.com/gphotosuploader/gphotos-uploader-cli#first-time-run). The third point is referring to the password for the [SecretsBackendType](https://github.com/gphotosuploader/gphotos-uploader-cli/blob/master/.docs/configuration.md#secretsbackendtype).

Thanks for the feedback.

**Comment by danrabinowitz** [comment]
FYI, this PR helps: https://github.com/gphotosuploader/gphotos-uploader-cli/pull/209

**Comment by barrkel** [comment]
Would also like to see movement on this, including #209 if it helps. The entire point of CLI access is to run via a cron job, if it needs interactive use I might as well use the web page.

Credential security is much less interesting to me since I'm using a Google account separately created just for sharing photos with family etc. A `0600` file is fine for my purposes.

**Comment by barrkel** [comment]
My workaround is using an expect script, along these lines:

```
#!/usr/bin/expect -f

set timeout 3600

spawn gphotos-uploader-cli push

expect "Enter the passphrase to open the token store: "

send -- "<the password>\r"

expect eof
```

This is much easier and more lightweight than running a whole docker container when it only needs executing once a day or so.

**Comment by pacoorozco** [comment]
I'm going to open this issue due to the traction it is having.

**Comment by pacoorozco** [comment]
Hi, Everything that you are pointing in this feedback has already been addressed.

1. auh process is not opening a browser, it's showing the URL instead
2. the encryption key could be set by env var. See [here](https://github.com/gphotosuploader/gphotos-uploader-cli/blob/master/.docs/configuration.md#environment-variables)
