### ISSUE TITLE
GIF and Video files are not deleted once they have been uploaded

### ISSUE THREAD

**Issue by nmrshll** [gphotosuploader/gphotos-uploader-cli#25]
GIF files are uploaded but never deleted from local disk

**Comment by pacoorozco** [comment]
GIF & Videos are not deleted because the methods that checks uploaded and local file are the same are broken:

* https://github.com/nmrshll/gphotos-uploader-cli/blob/5457068d42ff189235f1151aa557d252ce39ee77/filetypes/video.go#L10
* https://github.com/nmrshll/gphotos-uploader-cli/blob/5457068d42ff189235f1151aa557d252ce39ee77/filetypes/gif.go#L10

**Comment by pacoorozco** [comment]
Trying to fix this bug I've realised that **it's very difficult and expensive that to files are the same** before deleting the local one. The original code was doing different things depending the media type: [gif](https://github.com/nmrshll/gphotos-uploader-cli/blob/5457068d42ff189235f1151aa557d252ce39ee77/filetypes/gif.go#L10), [video](https://github.com/nmrshll/gphotos-uploader-cli/blob/5457068d42ff189235f1151aa557d252ce39ee77/filetypes/video.go#L10) and [image](https://github.com/nmrshll/gphotos-uploader-cli/blob/5457068d42ff189235f1151aa557d252ce39ee77/filetypes/image.go#L82)

* For **image** files: First the image is downloaded from Google Photos  :wastebasket: (this could take a bit, depending the size of the image, **a lot of bandwidth is wasted**), then *average hash* of the image is calculated (convert it in greyscale, resize it in 9x8 and calculate the average, **a lot of CPU is wasted**) and last the local hash and the remote hash, calculated previously, is compared using a [hamming function](https://en.wikipedia.org/wiki/Hamming_distance).
* For **gif** files: Again, the image is downloaded from Google Photos :wastebasket: (**same problem as above**) then a hash, a non-cryptological one, is calculated (**a lot of CPU is wasted**) and compared.
* For **video** files: The code is broken. It has been copied from GIF files so it's not working. :man_facepalming: 

One alternative came to my mind to simplify and fix the problem :bulb: :

Compare hashes of  the downloaded file and the local one. I don't like to download the image :wastebasket:, it seems a lot of time/bandwidth wasted (let's imagine to do the same for videos). 

But unfortunately the **hash of the downloaded file is different from the local one** :open_mouth:, this is due to Google Photos metadata, EXIF stripping, image & video processing... **So this alternative is not doable** :disappointed: 

A **less secure, but acceptable IMO** way to check the file was properly uploaded could be rely on the Google Photos response. **If Google says that the item was properly uploaded, we would remove it from local storage**.

And I'm thinking :thinking: if this `deleteAfterUpload` is an option that people are using a lot. **Are you using it?** **What do you think about my last alternative?**

**NOTE**: I'm going to disable the removal process. It's broken for GIF & Videos.

**Comment by fdubuisson** [comment]
Just discovered your tool (very useful for my use case) and would need to use this 'deleteAfterUpload' feature.
The option you propose (rely on the api result) looks ok to me. I don't see a reason to not trust the Google APIs :-)

**Comment by kissste** [comment]
I want to use it, please rely on google's API response.

**Comment by pacoorozco** [comment]
I'm returning from holidays, and this is gonna be my first issue to work on...
