### ISSUE TITLE
Albums are not being created, files being uploaded correctly 

### ISSUE THREAD

**Issue by darshan-pandya** [gphotosuploader/gphotos-uploader-cli#300]
**Describe the bug**
using v3.1.0 installed by brew, configured the tool to CreateAlbums

however, the albums are not being created. 

`Upload file '/Users/Downloads/zzz/PICS/random1/FILE029-1 copy.JPG' to album ''.`

job config as below 
![image](https://user-images.githubusercontent.com/52088430/119922263-51fa0600-bf24-11eb-97cc-e1ddefbce618.png)

**Comment by pacoorozco** [comment]
Hi @darshan-pandya 

Given your configurationm, this is the expected behavior. Folders are created from `SourceFolder`, so in your setup there are not folders inside `/Users/Downloads/zzz/PICS/random1`.

You can just change the `SourceFolder` to `/Users/Downloads/zzz/PICS`.

It's (more or less) explained [here](https://gphotosuploader.github.io/gphotos-uploader-cli/#/configuration?id=createalbums).

Thanks a lot for using this CLI :-D
