### ISSUE TITLE
Failed to push photo in github action

### ISSUE THREAD

**Issue by pingsutw** [gphotosuploader/gphotos-uploader-cli#311]
**Describe the bug**
Try to upload photos from GitHub action.
Error message:
```
  ./gphotos-uploader-cli/gphotos-uploader-cli push --config .
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.12/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.12/x64/lib
    GPHOTOS_CLI_TOKENSTORE_KEY: <MY_TOKEN>
[info]   Reading configuration from 'config.hjson'
[info]   Getting OAuth token for 'MY_GOOGLE_ACCOUNT'

Visit the following URL in your browser:
https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=547588427369-eh7rheli30bc81ec9a7iku60m6dnpjpl.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fphotoslibrary&state=state
```
**To Reproduce**
1. gphotos-uploader-cli push --config

**Expected behavior**
Upload photo to Google cloud

**Screenshots**

**Desktop & Client versions (please complete the following information):**
 - Operating System: [linux]
 - Version [v3.2.1]

**Additional context**
I want to use `gphotos-uploader-cli` in Github Action

**Comment by pacoorozco** [comment]
Hi @pingsutw 

We have covered this topic several times (e.g. #293 and #310) and I've realized that I should add it to the documentation.

This CLI **is not intended to work headless**. Due to some decisions taken during the development (authentication, secrets back-end...) the CLI **needs some kind of user interaction**.

The message that you're receiving is not an error or a bug. It's pointing you to the next step to complete the authorization which it's documented [here](https://gphotosuploader.github.io/gphotos-uploader-cli/#/getting-started?id=first-time-run). 

Apologies if you were not able to found it before.
