### ISSUE TITLE
Broken openid auth flow

### ISSUE THREAD

**Issue by paulirish** [gphotosuploader/gphotos-uploader-cli#337]
Perhaps more relevant to #331.. or #336 ...

I was just setting this up for the first time. I enabled the photos API and got openid creds. Then when trying the `auth` cli command, the auth flow ended up with access "blocked" and said I needed to complete the "verification process". 

Clicking around somewhere in credentials > "OAuth consent screen", I found "Test Users" and added myself. 
One that was done, I repeated and this time the openid auth flow completed successfully and secret saved.

_Thought: It's possible this all happened because I partially filled out the 'open id consent screen' form. TBH I never filled in any scoped or anything past that. But maybe since I started filling out the form I needed to come back and add in myself as a "Test user"?  I wonder if I hadn't touched the openid consent screen form, what would happen.._

Just sharing in case other new folks run into the same.

**Comment by pacoorozco** [comment]
The latest announced changes in Google has modified the "OAuth consent screen" configuration. As @paulirish was sharing you should use "External" (in Testing mode) and follow with the flow, which at some point force you to add your user to the "Test user" group.

The above workflow could be a workaround, but this #336 issue needs to be fixed permanently. Otherwise the authentication should be done every 7 days 😞
