### ISSUE TITLE
Several SecretBackendTypes not working for MacOS

### ISSUE THREAD

**Issue by dsem** [gphotosuploader/gphotos-uploader-cli#347]
**Describe the bug**
I am unable to use several of the Secret Backend Types, including `auto`, `keychain`, and `pass`.

I have the password-store tool installed and set up with my gpg keys, and the `pass` command is available in the environment that I'm running gphotos-uploader-cli.

When `SecretsBackendType` is set to `auto`, `gphotos-uploader-cli auth` works, but then when I try to push:

```
→ gphotos-uploader-cli push
[info]   Reading configuration from '/Users/<redacted>/.config/gphotos-uploader-cli/config.hjson'
[info]   Authenticating using token for '<redacted>'
gpg: public key decryption failed: No such file or directory
gpg: decryption failed: No such file or directory
[fatal]  unable to retrieve token, have you authenticated before?: token was not found
```

If I change `SecretsBackendType` to `keychain`, then I can't auth:

```
→ gphotos-uploader-cli auth
[info]   Reading configuration from '/Users/<redacted>/.config/gphotos-uploader-cli/config.hjson'
[error]  Token manager could not be started, err: Specified keyring backend not available
[fatal]  token manager could not be started, type:keychain, err: Specified keyring backend not available
```

If I change it to `pass`, it says the configuration is invalid:
```
→ gphotos-uploader-cli auth
[info]   Reading configuration from '/Users/<redacted>/.config/gphotos-uploader-cli/config.hjson'
[fatal]  invalid configuration at '/Users/<redacted>/.config/gphotos-uploader-cli/config.hjson': option SecretsBackendType is invalid, 'pass'
```

**Desktop & Client versions (please complete the following information):**
 - Operating System: MacOS Ventura
 - Version  3.5.0

**Comment by pacoorozco** [comment]
Hi @dsem 

Unfortunately I don't have a MacOS to test the different configurations shared by you. The only one I can test is the [pass](https://www.passwordstore.org/) one. 

I'm not using it but I guess I've found the problem. In order to make `pass` work with `gphotos-uploader-cli` some [extra configuration is needed](https://pkg.go.dev/github.com/99designs/keyring#Config): `PassDir`, `PassCmd` and `PassPrefix` but the CLI is not allowing to set these parameters :-( 

We should modify the [config schema](https://github.com/gphotosuploader/gphotos-uploader-cli/blob/cb3889f764854fe122c81d5bd032d0babc969045/internal/config/schema.go) to allow (and check) the proper configuration of the `pass` elements.
