### ISSUE TITLE
didn't find all files, please add ability to load file paths from txt.

### ISSUE THREAD

**Issue by mikebilly** [gphotosuploader/gphotos-uploader-cli#403]
I'm running this command:
```
import os
accepted_extensions = [".MOV", ".mp4", ".MP4", ".mkv", ".mov"] 
excluded_keywords = ["Trash", "Failed Videos", "trashed", "Recording", "ignore_video", "pending"]

directory = "/content/drive/MyDrive/All_Media"

def list_files(path='.'):
    file_list = []
    for entry in os.scandir(path):
        if entry.is_file():
            file_list.append(entry.path)
        elif entry.is_dir():
            file_list.extend(list_files(entry.path))
    return file_list
    
files = list_files(directory)

valid_videos_list = []
ignored_videos_list = []
valid_video_count = 0
for file_path in files:
    if os.path.splitext(file_path)[1] in accepted_extensions:
        valid = True
        for excluded_keyword in excluded_keywords:
            if excluded_keyword in file_path:
                valid = False
                break

        if valid:
            valid_video_count += 1
            valid_videos_list.append(file_path)
        else:
            ignored_videos_list.append(file_path)

print("Number of valid video files: {}".format(valid_video_count))
```
and it says:
```
Number of valid video files: 1695
```

Meanwhile ``gphotos-uploader-cli`` only found 1295 files:
```
[info]   Found 1295 items to be uploaded processing location '/content/drive/MyDrive/All_Media'.
```

this is my ``config.hjson`` file:
```
{
  APIAppCredentials:
  {
    ClientID: XXXXXXXXXX-XXXXXXXXXX.apps.googleusercontent.com
    ClientSecret: XXXXXXXXX-XXXXXXXXXXXXXX
  }
  Account: XXXXXXXXX@gmail.com
  SecretsBackendType: file
  Jobs:
  [
    {
      CreateAlbums: Off
      SourceFolder: /content/drive/MyDrive/All_Media
      DeleteAfterUpload: false
      IncludePatterns: ["**/*.MOV", "**/*.mp4", "**/*.MP4", "**/*.mkv", "**/*.mov"]
      ExcludePatterns: ["**/*Trash*", "**/*Failed Videos*", "**/*trashed*", "**/*Recording*", "**/*ignore_video*", "**/*pending*"]
    }
  ]
}
```
I also tried setting ``IncludePatterns: [ "_ALL_VIDEO_FILES_" ]`` but it still only found 1295 videos only.

Please check why ``gphotos-uploader-cli`` didn't find all files. And please add the ability to make ``gphotos-uploader-cli`` load the file paths from a file, like a txt file, for instance it can load from this file ``/content/drive/MyDrive/All_Media_valid_video_list.txt``:
```
path_valid = "/content/drive/MyDrive/All_Media_valid_video_list.txt"
with open(path_valid, "w") as output_file:
    for file_path in valid_videos_list:
        output_file.write(file_path + "\n")
```

That would be a very nice feature when ``gphotos-uploader-cli`` doesn't find all files, and when the user only wants to upload specific files without having to put them in a separate folder to upload.

**Comment by pacoorozco** [comment]
Hi @mikebilly 

I've run the command in my setup and all the files are listed. **Would you be able to run it again with the `--debug` flag to see which files are missing?**

I suggest to use the `--debug` and the `--dry-run`  flags and compare the list of discovered files with the list that you were comparing with. 

If there are still differences, **can you attach both files here?**

**Comment by pacoorozco** [comment]
I already read your feature request but I wanted to know if there was a bug too. I haven't been able to repressive your problem. 

All the tests are working as expected, filles are found without problems, that's why I want you to help me discover were the problem was

**Comment by pacoorozco** [comment]
Hi @mikebilly 

I have made several tests to reproduce the problem, **but none of them have succeeded**. I think the difference in the number of files in one code and the other is due to comparing two different procedures.

One evidence of this is that in `gphotos-uploader-cli` if a folder matches, it is completely ignored, while in the code it seems to apply only to files. There are other differences between the two codes that can explain the difference in the number of files to be uploaded.

Anyway, the way this CLI works to upload files based on `Jobs`, **it is intended to be used to faithfully update folders with images and videos in Google Photos**. 

The CLI has been designed this way from the beginning and a change like the one you propose is difficult to fit in the current code 😿  . However [there are other CLIs](https://github.com/int128/gpup)  that may help you achieve the same approach you're proposing.
